export const ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  COLLECTION: "collection",
  COMMUNITY: "/community",
  JOBS: "/jobs",
  TAGS: "/tags",
  PROFILE: (id: string) => `/profile/${id}`,
  TAG: (id: string) => `/tags/${id}`,
  ASK_QUESTION: "/ask-question",
  QUESTION: (id: string) => `/question/${id}`,
  CREATEJOB: "/jobs/create",
  JOBS_ID: (id: string) => `/jobs/${id}`,
};
